services:
  - body: Desplazamiento por toda la Comunidad de Madrid.
    icon: fa-car
    title: Entrenamiento Personal a domicilio
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-heart
    title: Entrenamiento de Rehabilitación
  - body: Rutinas de entrenamiento para el día a día.
    icon: fa-print
    title: Tablas de Entrenamiento
  - body: >-
      Todo lo que necesitas saber de una dieta sana y equilibrada, y consejos de
      nutrición.
    icon: fa-table
    title: Nutrición Deportiva y Suplementacion
  - body: >-
      Corrección de ejercicios, rutinas nuevas, seguimiento, etc todo
      supervisado en tu gimnasio de confianza.
    icon: fa-ball
    title: Entrenamiento Personal en gimnasios
  - body: Entrenamiento saludable y ameno hacia la gente que más queremos.
    icon: fa-face
    title: Entrenamiento Personal para gente mayor.
  - body: >-
      Mejorare tus marcas y conseguirás objetivos para lograr tu plaza en las
      oposiciones.
    icon: fa-arm
    title: Preparación de Oposiciones
