services:
  - body: Desplazamiento por toda la Comunidad de Madrid.
    icon: fa-car
    title: Entrenamiento Personal a domicilio
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-health
    title: Entrenamiento de Rehabilitación
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-plus
    title: Tablas de Entrenamiento
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-music
    title: Nutrición Deportiva y Suplementacion
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-print
    title: Entrenamiento Personal en gimnasios
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-wifi
    title: Entrenamiento Personal para gente mayor.
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-map-signs
    title: Preparación de Oposiciones
