services:
  - body: Desplazamiento por toda la Comunidad de Madrid.
    icon: fa-car
    title: Entrenamiento Personal a domicilio
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-heart
    title: Entrenamiento de Rehabilitación
  - body: Rutinas de entrenamiento para el día a día.
    icon: fa-print
    title: Tablas de Entrenamiento
  - body: >-
      Todo lo que necesitas saber de una dieta sana y equilibrada, y consejos de
      nutrición.
    icon: fa-table
    title: Nutrición Deportiva y Suplementacion
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-dumbells
    title: Entrenamiento Personal en gimnasios
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-smile
    title: Entrenamiento Personal para gente mayor.
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-map-signs
    title: Preparación de Oposiciones
